on:
  push:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew install TarasMazepa/stax/stax
          stax doctor

  install-x86:
    runs-on: ubuntu-latest
    container: i386/alpine:latest
    steps:
      - run: echo "hi"

