on:
  push:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13 ]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew install TarasMazepa/stax/stax
          stax help
          stax doctor

  install-linux-arm64v8:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run \
            -d \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/arm64/v8 \
            --name container \
            arm64v8/alpine:latest
          which docker
          docker version
          docker --version
          docker ps
          docker wait container
          docker exec container /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          docker exec container (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          docker exec container eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          docker exec container brew install TarasMazepa/stax/stax
          docker exec container stax help
          docker exec container stax doctor

  install-linux-arm32v7:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run \
            -d \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/arm/v7 \
            --name container \
            arm32v7/alpine:latest
          which docker
          docker version
          docker --version
          docker ps
          docker wait container
          docker exec container /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          docker exec container (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          docker exec container eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          docker exec container brew install TarasMazepa/stax/stax
          docker exec container stax help
          docker exec container stax doctor

  install-linux-arm32v6:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run \
            -d \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/arm/v6 \
            --name container \
            arm32v6/alpine:latest
          which docker
          docker version
          docker --version
          docker ps
          docker wait container
          docker exec container /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          docker exec container (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          docker exec container eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          docker exec container brew install TarasMazepa/stax/stax
          docker exec container stax help
          docker exec container stax doctor
