on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  install-from-source:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13 ]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew install --build-from-source Formula/stax.rb
          stax help
          stax doctor
          stax version

  install-from-source-linux-arm64v8:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - run: docker run -d -i --platform linux/arm64/v8 arm64v8/alpine:latest
