on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - env:
          TAG: ${{ inputs.tag }}
        run: echo "Tag: $TAG"
        
