on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $(ls)
      - run: |
          echo $(pwd)
      - run: |
          sed "s/tag: .*/tag: $TAG/" Formula/stax.rb
        env:
          TAG: ${{ inputs.tag }}
        
