on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
      dart_sdk_version:
        required: false
        type: string

env:
  TAG: ${{ inputs.tag }}
  DART_SDK_VERSION: ${{ inputs.dart_sdk_version }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
      - if: "${{ github.event.inputs.dart_sdk_version != '' }}"
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap dart-lang/dart
          brew info dart-lang/dart/dart@$DART_SDK_VERSION
          sed -i "s+'dart-lang/dart/dart@.*'+'dart-lang/dart/dart@$DART_SDK_VERSION'+" ./Formula/stax.rb
          git checkout -b update-dart-sdk-version-for-stax-to-$DART_SDK_VERSION
          git commit -a -m "Update dart sdk version for stax to $DART_SDK_VERSION"
          git push --set-upstream origin update-dart-sdk-version-for-stax-to-$DART_SDK_VERSION
          gh pr merge $(gh pr create -B main -f) --auto --squash
          git checkout HEAD~
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - if: "${{ github.event.inputs.tag != '' }}"
        run: |
          sed -i "s/version '.*'/version '$TAG'/" ./Formula/stax.rb
          sed -i "s/tag: .*/tag: '$TAG'/" ./Formula/stax.rb
          sed -i "s+/download/[^/]*/+/download/$TAG/+" ./Formula/stax.rb
          update_checksum () {
            checksum=$(curl -sL https://github.com/TarasMazepa/stax/releases/download/$TAG/$1.zip  | sha256sum | sed 's/  -//')
            sed -i "s+sha256.*$1+sha256 '$checksum' # $1+" ./Formula/stax.rb
          }
          update_checksum("macos-x64")
          update_checksum("macos-arm")
          update_checksum("linux-x64")
          git checkout -b update-stax-to-$TAG
          git commit -a -m "Update stax to $TAG"
          git push --set-upstream origin update-stax-to-$TAG
          gh pr merge $(gh pr create -B main -f) --auto --squash
          git checkout HEAD~
        env:
          GH_TOKEN: ${{ secrets.PAT }}
