on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  TAG: ${{ inputs.tag }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/tag: .*/tag: $TAG/" ./Formula/stax.rb
      - run: |
          git config --global user.name 'stax'
      - run: |
          git config --global user.email 'stax@staxforgit.com'
      - run: |
          git checkout -b update-stax-to-$TAG
      - run: |
          git commit -a -m "Update stax to $TAG"
      - run: |
          git push --set-upstream origin update-stax-to-$TAG
      - uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              owner,
              repo,
              head: "update-stax-to-${{ inputs.tag }}",
              base: 'main',
            });
