on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
      dart_sdk_version:
        required: false
        type: string

env:
  TAG: ${{ inputs.tag }}
  DART_SDK_VERSION: ${{ inputs.dart_sdk_version }}
  GH_TOKEN: ${{ github.token }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
      - if: "${{ github.event.inputs.dart_sdk_version != '' }}"
        run: |
          brew info dart@$DART_SDK_VERSION
          sed -i "s/'dart@.*'/'dart@$DART_SDK_VERSION'/" ./Formula/stax.rb
          git checkout -b update-dart-sdk-version-for-stax-to-$DART_SDK_VERSION
          git commit -a -m "Update dart sdk version for stax to $DART_SDK_VERSION"
          git push --set-upstream origin update-dart-sdk-version-for-stax-to-$DART_SDK_VERSION
          gh pr merge $(gh pr create -B main -f) --auto --squash
          git checkout HEAD~
      - if: "${{ github.event.inputs.tag != '' }}"
        run: |
          sed -i "s/tag: .*/tag: '$TAG'/" ./Formula/stax.rb
          git checkout -b update-stax-to-$TAG
          git commit -a -m "Update stax to $TAG"
          git push --set-upstream origin update-stax-to-$TAG
          gh pr merge $(gh pr create -B main -f) --auto --squash
          git checkout HEAD~
