on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  TAG: ${{ inputs.tag }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/tag: .*/tag: $TAG/" ./Formula/stax.rb
      - run: |
          git checkout -b update-stax-to-$TAG
      - run: |
          git commit -a -m "Update stax to $TAG" --author="stax <stax@staxforgit.com>"
      - run: |
          git push origin
      - run: |
          gh pr create -B update-stax-to-$TAG -H main
