on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  TAG: ${{ inputs.tag }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/tag: .*/tag: '$TAG'/" ./Formula/stax.rb
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
          git checkout -b update-stax-to-$TAG
          git commit -a -m "Update stax to $TAG"
          git push --set-upstream origin update-stax-to-$TAG
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          GH_TOKEN: ${{ github.token }}
