on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/tag: .*/tag: $TAG/" ./Formula/stax.rb
        env:
          TAG: ${{ inputs.tag }}
        
